In [2]:
import numpy as np

a = np.array([[0,1,2],[3,4,5]]) #shape (2,3)
b = np.array([[0,1],[2,3],[4,5]]) #shape (3,2)

print(a @ b) #or np.dot(a,b) #returns shape (2,2)

#   0 1 2  @  0 1  =  10 13
#   3 4 5     2 3     28 40
#             4 5

[[10 13]
 [28 40]]


In [3]:
print(b @ a) #or np.dot(b,a) #returns shape (3,3)

#   0 1  @  0 1 2  =  3  4  5
#   2 3     3 4 5     9  14 19
#   4 5               15 24 33

# code and comments by github.com/alandavidgrunberg

[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
